{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51791694.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51791694"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "I can confirm the issue; also, some additional issues surfaced once I tried adding a standalone test for ms2. I will update when both ms1 and ms2 have fully working tests.\r\n\r\nThank you.", "markup": "markdown", "html": "<p>I can confirm the issue; also, some additional issues surfaced once I tried adding a standalone test for ms2. I will update when both ms1 and ms2 have fully working tests.</p>\n<p>Thank you.</p>", "type": "rendered"}, "created_on": "2019-04-24T16:27:43.573104+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 51791694}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51792244.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51792244"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "Thanks for being responsive to this!", "markup": "markdown", "html": "<p>Thanks for being responsive to this!</p>", "type": "rendered"}, "created_on": "2019-04-24T17:08:56.933150+00:00", "user": {"display_name": "Stephen Blaskowski", "uuid": "{3e968357-25d3-4cb4-966a-3c128545fa5d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D"}, "html": {"href": "https://bitbucket.org/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/59ccf9ccc7f8e3d2572987cd74bfd186d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSB-4.png"}}, "nickname": "blasks", "type": "user", "account_id": "5c82e24b03a1f86544381a3c"}, "updated_on": null, "type": "issue_comment", "id": 51792244}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51796229.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51796229"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "Upon probing a little more I'm finding that the above change seems to resolve erroneous parsing for the first record in an ms2 file, but every record after fails to parse the 'precursor m/z' field. Is this one of the additional issues you identified? Could you point me to the break point for the problem?", "markup": "markdown", "html": "<p>Upon probing a little more I'm finding that the above change seems to resolve erroneous parsing for the first record in an ms2 file, but every record after fails to parse the 'precursor m/z' field. Is this one of the additional issues you identified? Could you point me to the break point for the problem?</p>", "type": "rendered"}, "created_on": "2019-04-24T23:40:00.094428+00:00", "user": {"display_name": "Stephen Blaskowski", "uuid": "{3e968357-25d3-4cb4-966a-3c128545fa5d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D"}, "html": {"href": "https://bitbucket.org/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/59ccf9ccc7f8e3d2572987cd74bfd186d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSB-4.png"}}, "nickname": "blasks", "type": "user", "account_id": "5c82e24b03a1f86544381a3c"}, "updated_on": null, "type": "issue_comment", "id": 51796229}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51807615.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51807615"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "Fix issue #39, disable indexing by default in ms1 and ms2, add ms2 tests\n\n\u2192 <<cset 6a13895e0d8c>>", "markup": "markdown", "html": "<p>Fix issue <a href=\"#!/levitsky/pyteomics/issues/39/bug-in-ms2-parser-_handle_s\" rel=\"nofollow\" title=\"Bug in ms2 parser _handle_S\" class=\"ap-connect-link\"><s>#39</s></a>, disable indexing by default in ms1 and ms2, add ms2 tests</p>\n<p>\u2192 &lt;&lt;cset <a href=\"#!/levitsky/pyteomics/commits/6a13895e0d8c\" rel=\"nofollow\" class=\"ap-connect-link\">6a13895e0d8c</a>&gt;&gt;</p>", "type": "rendered"}, "created_on": "2019-04-25T14:28:38.848060+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 51807615}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51807661.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51807661"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "Yes, the problem was that `_handle_S` was not called for subsequent scans. This should be fixed now. Please let me know if any issues remain.", "markup": "markdown", "html": "<p>Yes, the problem was that <code>_handle_S</code> was not called for subsequent scans. This should be fixed now. Please let me know if any issues remain.</p>", "type": "rendered"}, "created_on": "2019-04-25T14:30:31.125690+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 51807661}], "page": 1, "size": 5}