{"priority": "blocker", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "links": {"attachments": {"href": "data/repositories/levitsky/pyteomics/issues/7/attachments_page=1.json"}, "self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/7/watch"}, "comments": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments_page=1.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7/valueerror-in-pepxmlpy"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/7/vote"}}, "reporter": {"display_name": "Brian Mitchell", "uuid": "{25e274b5-bce3-4833-8d75-fa45f30d294c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D"}, "html": {"href": "https://bitbucket.org/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a0a7a43d9937b1f5a67e1fe737d21b82d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsBM-1.png"}}, "nickname": "bamitchell54", "type": "user", "account_id": "557058:e7383273-797d-4428-b366-c5bf02d7974e"}, "title": "ValueError in pepxml.py", "component": null, "votes": 0, "watches": 3, "content": {"raw": "I'm running Ubuntu 12.04 through a Virtual Box VM and noticed that when trying to run the example use of `pepxml.read()` shown here (http://pythonhosted.org/pyteomics/data.html), the following error resulted:\r\n\r\n\r\n```\r\n#!python\r\n\r\nFile \"/usr/local/lib/python2.7/dist-packages/pyteomics/pepxml.py\", line 90, in _get_info_smart\r\n    scores[name] = float(value)\r\nValueError: could not convert string to float: Normal\r\n```\r\n\r\n\r\nIt seems that value was a string and using the following change the problem resolved:\r\n\r\n\r\n```\r\n#!python\r\n\r\ntry:\r\n    scores[name] = float(value)\r\nexcept ValueError:\r\n    scores[name] = \"ValueError!\"\r\n```\r\n\r\n\r\nI've attached the pep.xml file used.  Let me know if you guys are aware of this, whether or not it is a bug, and if you need any more information from me.\r\n\r\nBrian", "markup": "markdown", "html": "<p>I'm running Ubuntu 12.04 through a Virtual Box VM and noticed that when trying to run the example use of <code>pepxml.read()</code> shown here (<a href=\"http://pythonhosted.org/pyteomics/data.html\" rel=\"nofollow\" class=\"ap-connect-link\">http://pythonhosted.org/pyteomics/data.html</a>), the following error resulted:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"n\">File</span> <span class=\"s2\">&quot;/usr/local/lib/python2.7/dist-packages/pyteomics/pepxml.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">90</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">_get_info_smart</span>\n    <span class=\"n\">scores</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">]</span> <span class=\"o\">=</span> <span class=\"nb\">float</span><span class=\"p\">(</span><span class=\"n\">value</span><span class=\"p\">)</span>\n<span class=\"ne\">ValueError</span><span class=\"p\">:</span> <span class=\"n\">could</span> <span class=\"ow\">not</span> <span class=\"n\">convert</span> <span class=\"n\">string</span> <span class=\"n\">to</span> <span class=\"nb\">float</span><span class=\"p\">:</span> <span class=\"n\">Normal</span>\n</pre></div>\n\n\n<p>It seems that value was a string and using the following change the problem resolved:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"k\">try</span><span class=\"p\">:</span>\n    <span class=\"n\">scores</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">]</span> <span class=\"o\">=</span> <span class=\"nb\">float</span><span class=\"p\">(</span><span class=\"n\">value</span><span class=\"p\">)</span>\n<span class=\"k\">except</span> <span class=\"ne\">ValueError</span><span class=\"p\">:</span>\n    <span class=\"n\">scores</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">]</span> <span class=\"o\">=</span> <span class=\"s2\">&quot;ValueError!&quot;</span>\n</pre></div>\n\n\n<p>I've attached the pep.xml file used.  Let me know if you guys are aware of this, whether or not it is a bug, and if you need any more information from me.</p>\n<p>Brian</p>", "type": "rendered"}, "assignee": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2014-02-04T21:11:08.070999+00:00", "milestone": null, "updated_on": "2014-02-14T09:22:28.840545+00:00", "type": "issue", "id": 7}