{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25/comments/45601706.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/25#comment-45601706"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "pyteomics 3.4 incompatible with current versions of pepxmltk and cythonize"}, "content": {"raw": "Thanks for looking into it. I've reported the issues on the bioconda-recipes github (including what you found about the `egg` vs `pyteomics` folder), since the issue only appear to be with installation through conda.", "markup": "markdown", "html": "<p>Thanks for looking into it. I've reported the issues on the bioconda-recipes github (including what you found about the <code>egg</code> vs <code>pyteomics</code> folder), since the issue only appear to be with installation through conda.</p>", "type": "rendered"}, "created_on": "2018-05-18T21:30:40.140137+00:00", "user": {"display_name": "mglubber", "uuid": "{559bde61-bb9f-484b-b183-1b21bb8b4bb0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B559bde61-bb9f-484b-b183-1b21bb8b4bb0%7D"}, "html": {"href": "https://bitbucket.org/%7B559bde61-bb9f-484b-b183-1b21bb8b4bb0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f188803c05340901eba88626b4b308d9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-0.png"}}, "nickname": "mglubber", "type": "user", "account_id": "5af0862cfd53c72c28995f3f"}, "updated_on": null, "type": "issue_comment", "id": 45601706}