{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51791694.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51791694"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "I can confirm the issue; also, some additional issues surfaced once I tried adding a standalone test for ms2. I will update when both ms1 and ms2 have fully working tests.\r\n\r\nThank you.", "markup": "markdown", "html": "<p>I can confirm the issue; also, some additional issues surfaced once I tried adding a standalone test for ms2. I will update when both ms1 and ms2 have fully working tests.</p>\n<p>Thank you.</p>", "type": "rendered"}, "created_on": "2019-04-24T16:27:43.573104+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 51791694}