{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39/comments/51796229.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/39#comment-51796229"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/39.json"}}, "type": "issue", "id": 39, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in ms2 parser _handle_S"}, "content": {"raw": "Upon probing a little more I'm finding that the above change seems to resolve erroneous parsing for the first record in an ms2 file, but every record after fails to parse the 'precursor m/z' field. Is this one of the additional issues you identified? Could you point me to the break point for the problem?", "markup": "markdown", "html": "<p>Upon probing a little more I'm finding that the above change seems to resolve erroneous parsing for the first record in an ms2 file, but every record after fails to parse the 'precursor m/z' field. Is this one of the additional issues you identified? Could you point me to the break point for the problem?</p>", "type": "rendered"}, "created_on": "2019-04-24T23:40:00.094428+00:00", "user": {"display_name": "Stephen Blaskowski", "uuid": "{3e968357-25d3-4cb4-966a-3c128545fa5d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D"}, "html": {"href": "https://bitbucket.org/%7B3e968357-25d3-4cb4-966a-3c128545fa5d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/59ccf9ccc7f8e3d2572987cd74bfd186d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSB-4.png"}}, "nickname": "blasks", "type": "user", "account_id": "5c82e24b03a1f86544381a3c"}, "updated_on": null, "type": "issue_comment", "id": 51796229}