{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33/comments/48692372.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/33#comment-48692372"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33.json"}}, "type": "issue", "id": 33, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Problems w/ creating DataFrame from X!Tandem file"}, "content": {"raw": "Hi, thank you for reporting this!\n\nIndeed, `tandem.DataFrame` is broken, my apologies. However, only the first error is reproduced on my files using the latest 4.0 version.\nWould you be able to attach an example file demonstrating the second problem? For now I have removed the first erroneous statement.", "markup": "markdown", "html": "<p>Hi, thank you for reporting this!</p>\n<p>Indeed, <code>tandem.DataFrame</code> is broken, my apologies. However, only the first error is reproduced on my files using the latest 4.0 version.\nWould you be able to attach an example file demonstrating the second problem? For now I have removed the first erroneous statement.</p>", "type": "rendered"}, "created_on": "2018-11-01T22:59:36.069146+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 48692372}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33/comments/48692403.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/33#comment-48692403"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33.json"}}, "type": "issue", "id": 33, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Problems w/ creating DataFrame from X!Tandem file"}, "content": {"raw": "(formatted the traceback)", "markup": "markdown", "html": "<p>(formatted the traceback)</p>", "type": "rendered"}, "created_on": "2018-11-01T23:04:39.067294+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 48692403}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33/comments/49773136.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/33#comment-49773136"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/33.json"}}, "type": "issue", "id": 33, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Problems w/ creating DataFrame from X!Tandem file"}, "content": {"raw": "Please feel free to reopen if this error occurs with the current version.", "markup": "markdown", "html": "<p>Please feel free to reopen if this error occurs with the current version.</p>", "type": "rendered"}, "created_on": "2019-01-07T15:48:27.113734+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 49773136}], "page": 1, "size": 3}