{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34/comments/48910596.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/34#comment-48910596"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34.json"}}, "type": "issue", "id": 34, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "parser fails on numbers in modX sequence"}, "content": {"raw": "I've created [a PR](https://github.com/mobiusklein/pyteomics.cythonize/pull/1) for `pyteomics.cythonize` with the same change.\n\nYes, the pyteomics fix will be included in 4.0 release, unless it turns out to cause any problems I haven't thought of.", "markup": "markdown", "html": "<p>I've created <a data-is-external-link=\"true\" href=\"https://github.com/mobiusklein/pyteomics.cythonize/pull/1\" rel=\"nofollow\">a PR</a> for <code>pyteomics.cythonize</code> with the same change.</p>\n<p>Yes, the pyteomics fix will be included in 4.0 release, unless it turns out to cause any problems I haven't thought of.</p>", "type": "rendered"}, "created_on": "2018-11-13T15:19:39.179706+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 48910596}