{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8085244.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8085244"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "Hi Brian,\n\nthank you for reporting! This is definitely a bug; we just hadn't come across a file that would show it until now. I'll add a fix for this as soon as possible, probably something similar to what you are showing above (but preserving the value). \n\n**Edit:** What I'm thinking of is the following:\n\n```\n#!python\n\ntry:\n    scores[name] = float(value)\nexcept ValueError:\n    scores[name] = value\n```\n\nP.S. I'm wondering why the line number is 90 in the traceback you are showing, because it's line 85 in all recent versions of pyteomics. Is it an older version, or have you added other changes? Just curious :)\n\nThanks again,\n\nLev", "markup": "markdown", "html": "<p>Hi Brian,</p>\n<p>thank you for reporting! This is definitely a bug; we just hadn't come across a file that would show it until now. I'll add a fix for this as soon as possible, probably something similar to what you are showing above (but preserving the value). </p>\n<p><strong>Edit:</strong> What I'm thinking of is the following:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"k\">try</span><span class=\"p\">:</span>\n    <span class=\"n\">scores</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">]</span> <span class=\"o\">=</span> <span class=\"nb\">float</span><span class=\"p\">(</span><span class=\"n\">value</span><span class=\"p\">)</span>\n<span class=\"k\">except</span> <span class=\"ne\">ValueError</span><span class=\"p\">:</span>\n    <span class=\"n\">scores</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">]</span> <span class=\"o\">=</span> <span class=\"n\">value</span>\n</pre></div>\n\n\n<p>P.S. I'm wondering why the line number is 90 in the traceback you are showing, because it's line 85 in all recent versions of pyteomics. Is it an older version, or have you added other changes? Just curious :)</p>\n<p>Thanks again,</p>\n<p>Lev</p>", "type": "rendered"}, "created_on": "2014-02-04T21:46:05.449286+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2014-02-04T22:04:24.681664+00:00", "type": "issue_comment", "id": 8085244}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8085680.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8085680"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "Lev,\n\nThat looks fine, I just wanted to include a special value so I could easily identify the affected key/value pairs in the output dict.  I'll implement this patch and let you know if I have any more issues.\n\nIt showed line 90 in the traceback because I put a few changes above it on my machine.  Good eye!\n\nThanks for the quick feedback,\nBrian", "markup": "markdown", "html": "<p>Lev,</p>\n<p>That looks fine, I just wanted to include a special value so I could easily identify the affected key/value pairs in the output dict.  I'll implement this patch and let you know if I have any more issues.</p>\n<p>It showed line 90 in the traceback because I put a few changes above it on my machine.  Good eye!</p>\n<p>Thanks for the quick feedback,\nBrian</p>", "type": "rendered"}, "created_on": "2014-02-04T22:21:14.981787+00:00", "user": {"display_name": "Brian Mitchell", "uuid": "{25e274b5-bce3-4833-8d75-fa45f30d294c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D"}, "html": {"href": "https://bitbucket.org/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a0a7a43d9937b1f5a67e1fe737d21b82d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsBM-1.png"}}, "nickname": "bamitchell54", "type": "user", "account_id": "557058:e7383273-797d-4428-b366-c5bf02d7974e"}, "updated_on": null, "type": "issue_comment", "id": 8085680}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8094536.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8094536"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "The proposed patch is implemented in commit 12050d4. I'll wait for some time before marking this as fixed.\n\nP.S. Also, if you think the custom changes you've made to the sources may be of use to others, I'll be happy to review your pull request. Or maybe an enhancement request for additional configuration options?\n\nAnyway, thanks for all your help so far.\n\nLev", "markup": "markdown", "html": "<p>The proposed patch is implemented in commit <a href=\"#!/levitsky/pyteomics/commits/12050d4\" rel=\"nofollow\" class=\"ap-connect-link\">12050d4</a>. I'll wait for some time before marking this as fixed.</p>\n<p>P.S. Also, if you think the custom changes you've made to the sources may be of use to others, I'll be happy to review your pull request. Or maybe an enhancement request for additional configuration options?</p>\n<p>Anyway, thanks for all your help so far.</p>\n<p>Lev</p>", "type": "rendered"}, "created_on": "2014-02-05T11:42:28.927738+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2014-02-05T11:42:43.470338+00:00", "type": "issue_comment", "id": 8094536}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8100712.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8100712"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "The project I'm working on might be of interest, but the changes I made to pepxml.py were simply for debugging purposes.  Basically, I'm using Pyteomics to compile information from a large number of mzML and pep.xml files into a simple database and using this data to simulate MS/MS.  I'm trying to develop criteria to build a smarter inclusion list and simulating MS/MS is much, much more efficient than running a bona fide MS/MS experiment every time I want to test a new model.  Is this something you guys would be interested in?\n\nBrian", "markup": "markdown", "html": "<p>The project I'm working on might be of interest, but the changes I made to pepxml.py were simply for debugging purposes.  Basically, I'm using Pyteomics to compile information from a large number of mzML and pep.xml files into a simple database and using this data to simulate MS/MS.  I'm trying to develop criteria to build a smarter inclusion list and simulating MS/MS is much, much more efficient than running a bona fide MS/MS experiment every time I want to test a new model.  Is this something you guys would be interested in?</p>\n<p>Brian</p>", "type": "rendered"}, "created_on": "2014-02-05T17:29:23.409429+00:00", "user": {"display_name": "Brian Mitchell", "uuid": "{25e274b5-bce3-4833-8d75-fa45f30d294c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D"}, "html": {"href": "https://bitbucket.org/%7B25e274b5-bce3-4833-8d75-fa45f30d294c%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a0a7a43d9937b1f5a67e1fe737d21b82d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsBM-1.png"}}, "nickname": "bamitchell54", "type": "user", "account_id": "557058:e7383273-797d-4428-b366-c5bf02d7974e"}, "updated_on": null, "type": "issue_comment", "id": 8100712}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8102766.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8102766"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "Oh, I see. That sounds like an interesting and promising idea. So you need to generate data with statistical properties derived from samples of the real data you have?\nDo you think we could be of help? If you'd like to discuss it over email, you can contact me at lev.levitsky<at>phystech.edu.\n\nLev", "markup": "markdown", "html": "<p>Oh, I see. That sounds like an interesting and promising idea. So you need to generate data with statistical properties derived from samples of the real data you have?\nDo you think we could be of help? If you'd like to discuss it over email, you can contact me at lev.levitsky&lt;at&gt;phystech.edu.</p>\n<p>Lev</p>", "type": "rendered"}, "created_on": "2014-02-05T19:49:25.395285+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2014-02-05T19:59:12.950771+00:00", "type": "issue_comment", "id": 8102766}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7/comments/8391631.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/7#comment-8391631"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/7.json"}}, "type": "issue", "id": 7, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "ValueError in pepxml.py"}, "content": {"raw": "Marking as fixed; feel free to comment or report a new issue if any problems arise.", "markup": "markdown", "html": "<p>Marking as fixed; feel free to comment or report a new issue if any problems arise.</p>", "type": "rendered"}, "created_on": "2014-02-14T09:22:28.883079+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 8391631}], "page": 1, "size": 6}