{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54482696.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54482696"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "Can confirm with last release and development versions on Python 2.\n\nThe suggested fix doesn't seem right for Python 3, though. We need to apply the \"ensure string\" logic somewhere, probably in or around `_handle_param()`.", "markup": "markdown", "html": "<p>Can confirm with last release and development versions on Python 2.</p>\n<p>The suggested fix doesn't seem right for Python 3, though. We need to apply the \"ensure string\" logic somewhere, probably in or around <code>_handle_param()</code>.</p>", "type": "rendered"}, "created_on": "2019-10-22T14:13:11.101823+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 54482696}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54483653.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54483653"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "A version of the suggested fix is applied in 80bb804 \\(with a version check\\), but we need to look around for more corner cases.\n\n\u200c", "markup": "markdown", "html": "<p>A version of the suggested fix is applied in <a href=\"#!/levitsky/pyteomics/commits/80bb804\" rel=\"nofollow\" class=\"ap-connect-link\">80bb804</a> (with a version check), but we need to look around for more corner cases.</p>\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2019-10-22T15:08:34.372183+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 54483653}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54483741.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54483741"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "Ok I did not test this with python 3 before - just did so \\(3.7\\) and it seem to work fine even without the \u201cfix\u201d there. But I also don\u2019t encounter errors with the `.encode('utf-8')` . \n\nBut I also made a very simple test \n\n\u200c\n\n```\nimport pyteomics.mzid as py_mzid\n\nmzid_path='test_umlaut.mzid'\nmzid_reader = py_mzid.MzIdentML(mzid_path)\n\ni = mzid_reader.iterfind('AuditCollection')\n\ni.next()\n```\n\n\u200c", "markup": "markdown", "html": "<p>Ok I did not test this with python 3 before - just did so (3.7) and it seem to work fine even without the \u201cfix\u201d there. But I also don\u2019t encounter errors with the <code>.encode('utf-8')</code> . </p>\n<p>But I also made a very simple test </p>\n<p>\u200c</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"kn\">import</span> <span class=\"nn\">pyteomics.mzid</span> <span class=\"kn\">as</span> <span class=\"nn\">py_mzid</span>\n\n<span class=\"n\">mzid_path</span><span class=\"o\">=</span><span class=\"s1\">&#39;test_umlaut.mzid&#39;</span>\n<span class=\"n\">mzid_reader</span> <span class=\"o\">=</span> <span class=\"n\">py_mzid</span><span class=\"o\">.</span><span class=\"n\">MzIdentML</span><span class=\"p\">(</span><span class=\"n\">mzid_path</span><span class=\"p\">)</span>\n\n<span class=\"n\">i</span> <span class=\"o\">=</span> <span class=\"n\">mzid_reader</span><span class=\"o\">.</span><span class=\"n\">iterfind</span><span class=\"p\">(</span><span class=\"s1\">&#39;AuditCollection&#39;</span><span class=\"p\">)</span>\n\n<span class=\"n\">i</span><span class=\"o\">.</span><span class=\"n\">next</span><span class=\"p\">()</span>\n</pre></div>\n\n\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2019-10-22T15:13:23.284749+00:00", "user": {"display_name": "Lutz Fischer", "uuid": "{7796ce7b-56d0-4b48-a5ee-2191230149f0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D"}, "html": {"href": "https://bitbucket.org/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5bc9ac295b8ba5286cb9d07d/f3ad5bf8-4343-4b38-bed9-3202f68f080d/128"}}, "nickname": "Lutz", "type": "user", "account_id": "5bc9ac295b8ba5286cb9d07d"}, "updated_on": null, "type": "issue_comment", "id": 54483741}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54493389.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54493389"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "Is it a problem that this hard-codes for UTF-8? What happens if other encoding schemes are used for the mzIdentML?", "markup": "markdown", "html": "<p>Is it a problem that this hard-codes for UTF-8? What happens if other encoding schemes are used for the mzIdentML?</p>", "type": "rendered"}, "created_on": "2019-10-23T07:22:57.400887+00:00", "user": {"display_name": "Lutz Fischer", "uuid": "{7796ce7b-56d0-4b48-a5ee-2191230149f0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D"}, "html": {"href": "https://bitbucket.org/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5bc9ac295b8ba5286cb9d07d/f3ad5bf8-4343-4b38-bed9-3202f68f080d/128"}}, "nickname": "Lutz", "type": "user", "account_id": "5bc9ac295b8ba5286cb9d07d"}, "updated_on": null, "type": "issue_comment", "id": 54493389}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54496413.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54496413"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "I don\u2019t think so. The file encoding is handled by the underlying XML parser, which produces decoded \\(Unicode\\) strings. That is actually the problem on Python2 where `unicode` is not `str`, which breaks the `str` constructor call signature. What we are doing in the fix is encoding the Unicode produced by the parser back into bytes.", "markup": "markdown", "html": "<p>I don\u2019t think so. The file encoding is handled by the underlying XML parser, which produces decoded (Unicode) strings. That is actually the problem on Python2 where <code>unicode</code> is not <code>str</code>, which breaks the <code>str</code> constructor call signature. What we are doing in the fix is encoding the Unicode produced by the parser back into bytes.</p>", "type": "rendered"}, "created_on": "2019-10-23T10:24:52.867174+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 54496413}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54497901.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54497901"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "Ah I see that is where the  PY2 from the commit comes into play. Anyway thank you.", "markup": "markdown", "html": "<p>Ah I see that is where the  PY2 from the commit comes into play. Anyway thank you.</p>", "type": "rendered"}, "created_on": "2019-10-23T11:47:28.220152+00:00", "user": {"display_name": "Lutz Fischer", "uuid": "{7796ce7b-56d0-4b48-a5ee-2191230149f0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D"}, "html": {"href": "https://bitbucket.org/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5bc9ac295b8ba5286cb9d07d/f3ad5bf8-4343-4b38-bed9-3202f68f080d/128"}}, "nickname": "Lutz", "type": "user", "account_id": "5bc9ac295b8ba5286cb9d07d"}, "updated_on": null, "type": "issue_comment", "id": 54497901}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/55038535.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-55038535"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2019-11-30T19:49:21.044794+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 55038535}], "page": 1, "size": 7}