{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/35/comments/49768132.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/35#comment-49768132"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/35.json"}}, "type": "issue", "id": 35, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "OrderedDict may be in reversed order on Py3.5"}, "content": {"raw": "The problem appears to be due to an error in loading the index from file. I'll open a pull request with the fix.", "markup": "markdown", "html": "<p>The problem appears to be due to an error in loading the index from file. I'll open a pull request with the fix.</p>", "type": "rendered"}, "created_on": "2019-01-07T11:17:55.380994+00:00", "user": {"display_name": "Joshua Klein", "uuid": "{919f0add-304d-4b9a-8889-d2622a3dbc96}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D"}, "html": {"href": "https://bitbucket.org/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7d0e70bc74f783efa621a2bdd228ca22d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-3.png"}}, "nickname": "mobiusklein", "type": "user", "account_id": "557058:ff82222f-afe5-4135-a1b7-8de99a00f669"}, "updated_on": null, "type": "issue_comment", "id": 49768132}