{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/14/comments/32208036.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/14#comment-32208036"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/14.json"}}, "type": "issue", "id": 14, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Bug in parsing of featureXML files"}, "content": {"raw": "Thank you, Lev.\nThis is a perfect solution. \nThe problem was pretty dumb, actually. It looks like OpenMS guys start changing the schema for featureXML a bit. ", "markup": "markdown", "html": "<p>Thank you, Lev.\nThis is a perfect solution. \nThe problem was pretty dumb, actually. It looks like OpenMS guys start changing the schema for featureXML a bit. </p>", "type": "rendered"}, "created_on": "2016-11-16T13:26:14.514447+00:00", "user": {"display_name": "Vladimir Gorshkov", "uuid": "{b5bdbfd0-9f35-4deb-99c4-bcf5c21ce1dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bb5bdbfd0-9f35-4deb-99c4-bcf5c21ce1dd%7D"}, "html": {"href": "https://bitbucket.org/%7Bb5bdbfd0-9f35-4deb-99c4-bcf5c21ce1dd%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/5e491fff15581a7cddd52a31c51a4ac7d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsVG-4.png"}}, "nickname": "caetera", "type": "user", "account_id": "557058:86c8a926-bff2-4418-87d2-38e26a677933"}, "updated_on": "2016-11-16T14:31:06.502409+00:00", "type": "issue_comment", "id": 32208036}